### ISSUE TITLE
How have you integrated .clang_tidy?

### ISSUE THREAD

**Issue by juliangaal** [hezicyan/nvchad#1]
How have you integrated clang tidy into nvchad? I assume during the clangd initialization? I am having a hard time setting this up.

Thanks for you help.

**Comment by hezicyan** [comment]
Ahh sorry i never expected someone will look into my config.

Well I honestly don't have a good method too. For me, I just put the .clang-tidy file here for a backup.

But here may be some advices to make it work. Every time you start a new project, you can create a .clang-tidy in the root directory of your project. If you want it to be working for all your scripts, you may try copying it to the user home directory, i.e. `~/.clang-tidy`

I don't know if this will help, sorry for insufficient preparation.

**Comment by hezicyan** [comment]
And I did try to integrate it using clangd args, but only to sadly find it deprecated, you can refer to [this](https://discourse.llvm.org/t/enabling-clang-tidy-checks-in-clangd/4906). It seems to be impossible to enable clang-tidy checks through command args in the newest version of clangd.

**Comment by juliangaal** [comment]
I think this is the way now: Look down at "root_dir" [here](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#clangd). I guess it picks up the .clang-tidy file in the root directory, the same way LSP uses the compile_commands.json file from the root directory.

Have you set up neovim to apply clang-format on every file save by chance?

**Comment by hezicyan** [comment]
> I think this is the way now: Look down at "root_dir" [here](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#clangd). I guess it picks up the .clang-tidy file in the root directory, the same way LSP uses the compile_commands.json file from the root directory.

If I didn't misunderstand, this pityfully cannot be editable in only neovim configs, either. And I'm currently using methods like this, that is I copied my `.clang-tidy` to `~/.clang-tidy` so that it can work with all my single scripts.

> Have you set up neovim to apply clang-format on every file save by chance?

It's not "by chance" though, I did it "on purpose". [Here](https://github.com/hezicyan/nvchad/blob/32dc37a87a1e5cafa0c1418dfc82ca05dea224c3/configs/null-ls.lua#L32-L48) I set an augroup called `LspFormatting` for auto saving.

If you don't want this feature, you can simply delete those lines.

If you want to toggle auto saving, you can use [`vim.api.nvim_del_augroup_by_name`](https://neovim.io/doc/user/api.html#nvim_del_augroup_by_name()) to delete this augroup in order to disable auto saving. And create augroup and autocmds again to enable auto saving. You can also check out [this](https://github.com/ayamir/nvimdots/blob/b314ead809eb535e0223b562c1f88c7053c7712d/lua/modules/configs/completion/formatting.lua#L36-L87) for a specific example.

*And sadly to inform you, this repo may be put on hold for a long time without updating due to my study. But if you need, I'd be very glad to be here to help.*
